### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by Lily-Shawn** [taesoobear/IPCDNNwalk#1]
Sorry ,I run your project in Vmware Ubuntu, but after I install all the dependencies.The program is failed.This is the error info:

RuntimeError: FATAL: module compiled as little endian, but detected different endianness at runtime
pFileName=../Resource/motion.lua
Xdbe not supported, faking double buffer with pixmaps.
pFileName=../Resource/loader.lua
test:0
aspect Ratio 1.706667
pFileName=../Resource/scripts/loadBG_default.lua
pFileName=gym_walkCDM/testWalkV2_FA.lua
Cart	Pole
1	59.999663	0.947889	13.643121
Info:	{
 {[0]={0.000, 0.000, 1.000, 0.000, }
 {[1]={0.000, 0.000, 0.000, 1.000, }
 {[2]={-0.000, 35.772, -0.000, -0.000, }
 {[3]={-0.000, 38.367, -0.000, -0.000, }
}
	{
 {[0]={0.000, }
 {[1]={0.000, }
 {[2]={0.076, }
 {[3]={0.064, }
}
	{
 {[0]={0.000, 0.000, 0.000, 0.000, }
 {[1]={0.000, 50.000, 0.000, 0.000, }
 {[2]={0.000, 0.000, 50000.000, 0.000, }
 {[3]={0.000, 0.000, 0.000, 0.000, }
}
	{
 {[0]={1.000, }
}
	{
 {[0]={-0.000, 2383.650, -223.607, 646.147, }
}

Info:	{
 {[0]={0.000, 0.000, 1.000, 0.000, }
 {[1]={0.000, 0.000, 0.000, 1.000, }
 {[2]={-0.000, 35.772, -0.000, -0.000, }
 {[3]={-0.000, 38.367, -0.000, -0.000, }
}
	{
 {[0]={0.000, }
 {[1]={0.000, }
 {[2]={0.076, }
 {[3]={0.064, }
}
	{
 {[0]={0.000, 0.000, 0.000, 0.000, }
 {[1]={0.000, 50.000, 0.000, 0.000, }
 {[2]={0.000, 0.000, 50000.000, 0.000, }
 {[3]={0.000, 0.000, 0.000, 0.000, }
}
	{
 {[0]={1.000, }
}
	{
 {[0]={-0.000, 2383.650, -223.607, 646.147, }
}

{
	[touchDown]=(userdata), 
	[touchOff]=(userdata), 
}
[0.252778,0.116667,0.236111,]
[0.250000,0.150000,0.205556,]
0.60555555555556
{
	[touchDown]=(userdata), 
	[touchOff]=(userdata), 
}
[0.155556,0.116667,0.122222,]
[0.075000,0.150000,0.169444,]
0.39444444444444
startpos	0 0.95 0	0 0 0
oeval:0.91349022529804 dim:4
(2,4)-CMA-ES(mu_eff=1.6), Ver="3.10.00.beta", dimension=4, diagonalIterations=0, randomSeed=862967323 (Fri Jun 11 19:14:44 2021) 
timing	0	table: 0x563b6e08f730
140.021	ms replan_pend.
Evidence 31.670631 Likelihood 3.143137
7.542	nn.
10.357	ms nn.
ctor finished
段错误 (核心已转储)

**Comment by taesoobear** [comment]
Hello,
You can safely ignore the following runtime error.
RuntimeError: FATAL: module compiled as little endian, but detected
different endianness at runtime.

Does the render window open up? If so, then I guess your program is running
fine. You do not need to read the followings. Let me know if you have any
other questions.

If it does not, remove work/ogre_linux*.cfg and run again.
If the configuration dialog opens, make sure you choose opengl render
system instead of opengl 3+ render system.
If it still doesn't work, edit Resource/ogreconfig_linux.cfg and
Resource/ogreconfig_linux12.cfg and edit the following line:
enagleLog 0
->
enagleLog 1

Then, run again. This time, the error log will be written in the
work/Ogre.log file.
You can show me the log file.
Best regards,

Taesoo Kwon.

**Comment by Lily-Shawn** [comment]
Sorry to interupt again. After I input command "python3 test_walk2.py gym_walkCDM/testWalkV2_FA.lua".The system will open a dailog window.But it will close soon.(after few secons.).And My vmware will send system error.(the detail is python 3.8 run error).So,is it possible that this programe can not run in virtual machine?
By the way I remove the "work/ogre_linux*.cfg".
I very like your paper "Fast and Flexible Multilegged Locomotion Using Learned Centroidal Dynamics". You did a wonderful work.I hope we will read your paper in Siggraph in the future.

**Comment by taesoobear** [comment]
Okay, I can confirm that IPCDNNwalk does not work in the vmware properly.
But interestingly, if I debug build the project, it runs fine (albeit
slowly).
You can try to debug build the project by using "make debug" in the src
folder.
So, it seems that there is a bug in the project. But this bug does not
appear in my other normal installations. Anyway, I will try to fix this
issue later when I have time.
Best regards,

Taesoo.

**Comment by taesoobear** [comment]
I fixed this bug. It was a minor bug. (A boolean function in the IK solver did not return any boolean value.)
