### ISSUE TITLE
how can i implement the other awesome motion?

### ISSUE THREAD

**Issue by Colinsnow1** [taesoobear/IPCDNNwalk#2]
Thanks for awesome work and open code! 
However, When i run the code following the README.md on mac, it seem to show only walk and run motion. So how can i get other motion like jump, SuperFlips, Humanoid-Push, etc.. It seem to lack some folders showed in screenshots(see below). Really looking forward to your reply！Thanks again!

![image](https://user-images.githubusercontent.com/11901126/123378786-c5dd0c00-d5bf-11eb-919a-aa8145e10574.png)

**Comment by taesoobear** [comment]
I am sorry but many of the motions are commercial. (UE4_Mobility1 dataset.)
Also, this project only includes the DNN implementation which currently works only for walking and running motions.
